# Generated by Django 6.0.6 on 2026-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_college_email_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
